# Generated by Django 5.0.1 on 2024-03-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_info_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='expenditure',
        ),
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
