# Generated by Django 5.0.1 on 2024-03-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_user_info_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
